
        name: student project

on: push

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v4

      - name: Greet and count files
        env:
          STUDENT_NAME: ${{ vars.STUDENT_NAME }}
        run: |
           echo "Student Study Planner workflow is working!"